# Generated by Django 4.2.16 on 2024-10-07 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('splash', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prospect',
            name='published_date',
        ),
    ]
